### ISSUE TITLE
Desktop Duplication get buffer

### ISSUE THREAD

**Issue by AhmedX6** [hecomi/uDesktopDuplication#15]
Hello!

I would like to implement my own mirroring protocol, I'm trying to use Windows Desktop Duplication API for the client. https://msdn.microsoft.com/en-us/library/windows/desktop/hh404487(v=vs.85).aspx

My server is an Android device with an OpenGL surface to display the buffer.

I send only when desktop pixels are modified. I would like to retrieve a buffer with position of pixel that has been moved and send only that to the Android device. Is it possible to do it with the Desktop Duplication API ?

Thank you for your help !

**Comment by hecomi** [comment]
Desktop Duplication API provides dirty rects and move rects as written in the document. Using dirty rects as update areas is simple and nice method as your first step, I think.

**Comment by AhmedX6** [comment]
The problem is how to get the buffer of pixels that I have to send ?

**Comment by hecomi** [comment]
`IDXGIOutputDuplication` has `GetFrameDirtyRects()` and you can get `RECT` list through this API. 

- https://msdn.microsoft.com/en-us/library/windows/desktop/hh404619(v=vs.85).aspx

Please see the implementation of `Duplicator.cpp` as your reference.

- https://github.com/hecomi/uDesktopDuplication/blob/master/Plugins/uDesktopDuplication/uDesktopDuplication/Duplicator.cpp

The question seems to be a general one and is not related to this plugin. So I closed this issue.

**Comment by AhmedX6** [comment]
Thank you very much for your answer.
I do not know if you can or not to help me by e-mail or skype to implement this API on a QT project. This is a final project in computer engineering and I really need help. I will never thank you enough ...

I already encounter difficulties on a structure that would be unrecognized while the DirectX paths are added: DXGI_OUTDUPL_FRAME_INFO yet I have included <dxgi1_2.h> and the -ldxgi is in my .pro file.
