### ISSUE TITLE
How can i make the screen interactable?

### ISSUE THREAD

**Issue by lukas2005** [hecomi/uDesktopDuplication#19]
Hey on the animation you have in the readme file you can click on stuff how can i do that? + how could i do keyboard input?

**Comment by lachlansleight** [comment]
It's just a render of what's on your desktop - windows are interactable just like they normally are with the keyboard and mouse. 

You need to make sure you have Unity set to 'Run in Background' under the Player Settings so that when you alt+tab to other windows, your Unity app keeps running.

**Comment by lukas2005** [comment]
Well I mean interactable inside of unity.

**Comment by lachlansleight** [comment]
Well...no, it doesn't allow you to do that.

**Comment by lukas2005** [comment]
k
