### ISSUE TITLE
Can't get a texture on HiDPI envrionment.

### ISSUE THREAD

**Issue by Santarh** [hecomi/uDesktopDuplication#20]
Run uDesktopDuplication example scenes but I have got gray textures.

- Error Log
```
[uDD::Log][2018-05-30 01:34:45] Start
[uDD::Log][2018-05-30 01:34:45] Duplicator::Initialize() => OK.
[uDD::Log][2018-05-30 01:34:45]     ID    : 0
[uDD::Log][2018-05-30 01:34:45]     Size  : (2560, 1440)
[uDD::Log][2018-05-30 01:34:45]     DPI   : (109, 109)
[uDD::Log][2018-05-30 01:34:45]     Rot   : Landscape
[uDD::Err][2018-05-30 01:34:45] Monitor::Render() => Texture sizes are defferent.
[uDD::Err][2018-05-30 01:34:45]     Source : (3840, 2160)
[uDD::Err][2018-05-30 01:34:45]     Dest   : (2560, 1440)
```

- Environment
  - uDesktopDuplication v1.5.2
  - Windows 10 Version 1709
  - 1 Display (Resolution 3840x2160)
  - HiDPI 150%

![image](https://user-images.githubusercontent.com/328204/40673033-85b8b3e2-63ab-11e8-97a8-eb584c0704d1.png)

**Comment by Santarh** [comment]
日本語で失礼します。

ディスプレイの解像度や HiDPI の設定はまったく弄らずに Windows を再起動して
再度試したところ、正常に動作しました。
ただし、上記のエラー状態は再現しなくなってしまいました。
少々不可解ですが、Close させていただきます。

**Comment by hecomi** [comment]
ご連絡ありがとうございます。

#17 でも同じ症状が報告されていたのですが、ある .exe に対して初回起動した際に頂いたログのように異なるディスプレイサイズが API から報告される既知のバグが存在しています。この際、無理やりサイズを書き換えたとしても正常に DDA の結果が得られません。

また、これは「初回」起動だけ生じ、同じ .exe に対しては 2 度目の起動以降は起きないようです。原因は以前調査中です。

**Comment by Santarh** [comment]
ご返答ありがとうございます。 #17 の方、タイトルで見逃しておりました。
また発生条件に関しても理解できました。ありがとうございます。
