### ISSUE TITLE
Unity5.6.3f1でPropertyToIDがおこられる

### ISSUE THREAD

**Issue by TsubokuLab** [hecomi/uDesktopDuplication#26]
Unity5.x系だとTexture.csのPropertyToIDで怒られる？
StartかAwakeで初期化すれば問題なかった。

> PropertyToID is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'Texture' on game object 'Monitor Board'.
> See "Script Serialization" page in the Unity Manual for further details.
> UnityEngine.Shader:PropertyToID(String)
> uDesktopDuplication.Texture:.ctor() (at Assets/uDesktopDuplication/Scripts/Texture.cs:286)

**Comment by hecomi** [comment]
ご報告ありがとうございます！
