### ISSUE TITLE
Tripple spanned portrait monitors: Monitor::Render() => Texture sizes are defferent

### ISSUE THREAD

**Issue by flanagak** [hecomi/uDesktopDuplication#3]
I have a triple monitor setup with all 3 in portrait orientation.
I am using a GTX 1070 and I have these 3 monitors spanned so it appears in Windows as a single 3420x1920 monitor.

It appears that in the Monitor::Render() method the _resource_ object is not taking into account monitor orientation so the surface returned from AquireNextFrame is portrait and does not match the _unityTexture_ height and width.

Here is the uDesktopDuplication.log output:
[uDD::Log][2016-11-25 16:07:05] Start
[uDD::Log][2016-11-25 16:07:05] Monitor::Initialize() => OK.
[uDD::Log][2016-11-25 16:07:05]     ID    : 0
[uDD::Log][2016-11-25 16:07:05]     Size  : (3240, 1920)
[uDD::Log][2016-11-25 16:07:05]     DPI   : (88, 88)
[uDD::Err][2016-11-25 16:07:05] Monitor::Render() => Texture sizes are defferent.
[uDD::Err][2016-11-25 16:07:05]     Source : (1920, 3240)
[uDD::Err][2016-11-25 16:07:05]     Dest   : (3240, 1920)
[uDD::Err][2016-11-25 16:07:05] Cursor::UpdateTexture() => surface->Map() failed.
[uDD::Log][2016-11-25 16:07:29] Stop

**Comment by hecomi** [comment]
Thanks for the report.

Actually, the plugin checks the orientation of the monitor and creates a texture which matches it (in C#). In my environment, it works well for all orientations (landscape, portrait, and flipped)...

If the monitor is portrait, the size should be reported as (1920, 3240), but from the log, your monitor seems to report it is landscape. I think this is the case that I have not considered. Could you give me more information (OS, Eyefinity, any other display settings)? And I'll add more logs into the plugin code to detect the problem.

**Comment by flanagak** [comment]
Thanks for the quick response.

OS: Windows 10 - 64 bit
Graphics: GTX 1070
Monitors: ASUS VE258 (16:9  |  25"  | 1080p)
Normal Configuration:  NVidia Surround enabled - spanning all 3 monitors (Same thing as Eyefinity)
Individual resolution: 1080x1920
Spanned resolution: 3420x1920
Individual Orientation: Portrait
Spanned Orientation: Landscape


I tested breaking the NVidia Surround, so Windows sees all 3 monitors, and the sample works as expected.

I think the issue is coming from the fact the each monitor by itself is portrait, but when NVidia Surround is enabled the overall orientation is landscape since I have 3 connected together.

**Comment by hecomi** [comment]
Thanks a lot!
I'll try the NVIDIA Surround in my environment.

**Comment by hecomi** [comment]
I've tested NVIDIA Surround and the bug you reported could be re-generated. And it has been fixed in my environment. Could you test the latest build?
- https://developer.cloud.unity3d.com/share/ZyrN1CznhZ/

**Comment by flanagak** [comment]
Tested with the compiled exe in the link and I get an "Access Violation" and it crashes.

_Unity Player [version: Unity 5.4.2f1_94e3a60ee258]

uDesktopDuplication.dll caused an Access Violation (0xc0000005)
  in module uDesktopDuplication.dll at 0033:c20591ff.

Error occurred at 2016-11-26_070854.
C:\Users\flana\Downloads\hecomi-udesktopduplication-x86_64-56-uDesktopDuplication\uDesktopDuplication.exe, run by flana.
27% memory in use.
8172 MB physical memory [5920 MB free].
10156 MB paging file [7073 MB free].
134217728 MB user address space [134216998 MB free].
Read from location 00000030 caused an access violation.

Context:
RDI:    0x01284ac0  RSI: 0x00000000  RAX:   0x00000000
RBX:    0x10d79900  RCX: 0x10d425c0  RDX:   0x0bd5ebc8
RIP:    0xc20591ff  RBP: 0x0bd5ea10  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0x0bd5e900  SegSs: 0x0000002b
R8:    0x0bd5ea18  R9: 0x0e399550  R10:   0x00000000
R11:    0x0bd5ea80  R12: 0x10d425c0  R13:   0x06632a00
R14:    0x00000000  R15: 0x00000000_


I then pulled the latest source and tried starting up Unity with the "Multiple Monitor Roudly" scene and much like the exe I do see an initial image of my screen now, but it never updates.

When running from unity the uDesktopDuplication.log is filled with the following:
_[uDD::Log][2016-11-26 07:20:00] Start
[uDD::Log][2016-11-26 07:20:00] Monitor::Initialize() => OK.
[uDD::Log][2016-11-26 07:20:00]     ID    : 0
[uDD::Log][2016-11-26 07:20:00]     Size  : (3240, 1920)
[uDD::Log][2016-11-26 07:20:00]     DPI   : (88, 88)
[uDD::Err][2016-11-26 07:20:45] Cursor::UpdateTexture() => box is out of area.
[uDD::Err][2016-11-26 07:20:45]     (1890, 2922) ~ (1922, 2954) > (1920, 3240)
[uDD::Err][2016-11-26 07:20:45] Cursor::UpdateTexture() => box is out of area.
[uDD::Err][2016-11-26 07:20:45]     (1919, 2919) ~ (1951, 2951) > (1920, 3240)
[uDD::Err][2016-11-26 07:20:45] Cursor::UpdateTexture() => box is out of area.
[uDD::Err][2016-11-26 07:20:45]     (1919, 2923) ~ (1951, 2955) > (1920, 3240)
[uDD::Err][2016-11-26 07:20:45] Cursor::UpdateTexture() => box is out of area.
[uDD::Err][2016-11-26 07:20:45]     (1919, 2924) ~ (1951, 2956) > (1920, 3240)_

**Comment by flanagak** [comment]
So after pulling the latest and doing the above noted testing.
I opened up the C++ plugin, built it and then attached Visual Studio to Unity so I could step through the DLL.
After I built the plugin locally I no longer am getting the Cursor::UpdateTexture() error in the logs and the prefab scene is working with my monitor setup now.

**Comment by hecomi** [comment]
Thanks for the test! Other user in Twitter has also reported the Access Violation error and it's one of the biggest bugs that I want to fix asap. I think it is not caused `Cursor::UpdateTexture()` because it does `return` soon after the log in the code. And in some cases, errors don't occur in Unity Editor but only in Standalone builds. So if possible, could you attach the process to the build and check the line of the crash point?

**Comment by flanagak** [comment]
I tried to open up the crash dump file, but I don't have the matching .pdb so all I get is disassembly.

I will try taking my Unity project and making a stand alone and see if I can reproduce the error and get you the stack trace of where it crashed.

**Comment by hecomi** [comment]
I finished the refactoring in v1.4.0. So could you try it if you have time?
- https://github.com/hecomi/uDesktopDuplication/releases/tag/v1.4.0

**Comment by flanagak** [comment]
Yup I saw last night my time that you realeased it.

I did import 1.4 into my project and works great.

Thanks
Kevin Flanagan
-flanagak-

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Dec 2, 2016 at 8:41 AM -0800, "hecomi" <notifications@github.com<mailto:notifications@github.com>> wrote:


I finished the refactoring in v1.4.0. So could you try it if you have time?

  *   https://github.com/hecomi/uDesktopDuplication/releases/tag/v1.4.0

-

**Comment by hecomi** [comment]
Thanks so much!
