### ISSUE TITLE
Mouse Cursor gets heavily distorted on the right side of the screen

### ISSUE THREAD

**Issue by Xiexe** [hecomi/uDesktopDuplication#33]
There is an area on the right hand side of the screen where if the cursor is within it, it will get heavily distorted.

This may also be the cause of another issue, in which the cursor turns into a blank box and the capture stops updating, this only happens on some monitors, and only affects that one monitor. Re-initializing the API will fix that.

Here's a log from another users system that has a bunch of CreateTexture2D() failed. and Map() failed in it.

[uDesktopDuplication.log](https://github.com/hecomi/uDesktopDuplication/files/4251408/uDesktopDuplication.log)

**Comment by hecomi** [comment]
Thank you for the report. I'll check it in my environment soon.

**Comment by hecomi** [comment]
I've fixed the distortion bug but couldn't reproduce the performance problem in my PC. Could you check the latest version?
[uDesktopDuplication-v1.6.3.zip](https://github.com/hecomi/uDesktopDuplication/files/4333128/uDesktopDuplication-v1.6.3.zip)

**Comment by Xiexe** [comment]
will check soon! thank you!

**Comment by Xiexe** [comment]
Seems like this fixes both issues I was having. Thanks!
